### ISSUE TITLE
Build system can not find WSL2 path

### ISSUE THREAD

**Issue by dotnetCarpenter** [SublimeText/WslBuild#1]
<kbd>Ctrl</kbd>+<kbd>B</kbd>

```
/bin/bash: line 0: cd: //wsl$/Ubuntu/home/dotnet/projects/legaliser/legaliser-website: No such file or directory
/bin/bash: ./dev.sublime-build: Permission denied
[Finished in 486ms]
```

_//wsl$/Ubuntu/home/dotnet/projects/legaliser/legaliser-website_ is the correct full path.

In the _legaliser-website_ directory I have a `dev.sublime-build`, that Sublime picks up.

```json
{
	"target": "wsl_exec",
	"cancel": {"kill": true},
	"wsl_cmd": "npm run dev",
	"wsl_working_dir": "./legaliser-website"
}
```
_dev.sublime-build has `-rw-r--r--` like all other files (644)._

## Versions

Sublime Text Build 4152

WslBuild v0.1.0

**Comment by deathaxe** [comment]
You are running ST on Windows 10/11 with nodejs and your project located within WSL?

`wsl_exec` calls `cd $wsl_working_dir` to set the working directory within WSL environment, before executing the `wsl_cmd`. It should use the given value of `"wsl_working_dir"` as is. I don't currently see why it is expanded to `//wsl$/Ubuntu/...`.

Using your build script results in following error on my box, because the given path most likely not existing in the current working directory.

```
/bin/bash: line 1: cd: ./legaliser-website: No such file or directory
```

Actually I've never seen a path like //wsl$/Ubuntu before. I am however aware of `\\wsl.localhost\<distribution>\...` to access WSL filesystem using windows applications. This paths wouldn't however be available from within WSL.

It also appears bash tries to execute the `dev.sublime-build` instead of given `wsl_cmd`, which doesn't happen on my box eighter, even with your wrong notation.

_As a side note: `"wsl_cmd": ["npm", "run", "dev"]` is the only supported format, at the moment._

Finally WslBuild provides some extra variables, does some path translations and executes `wsl cd <wsl_working_dir>; <wsl_cmd>` via ST's default build system.

**Comment by deathaxe** [comment]
`\\wsl$\<distro>` seems to be the legacy notation still used by Windows 10.

A v0.2.0 has been pushed, which adds support for this notation and enables support for `wsl_cmd` to be a normal string.

**Comment by dotnetCarpenter** [comment]
Wow - that was fast! I will download v0.2 and try again. I was still answering you....

------------------------------

Yes, ST on Win10 with nodejs 18 installed in Ubuntu 20.04.6 LTS, WSL2.

I open ST through the Terminal with `cd projects/legaliser/legaliser-website` and `subl .`

`\\wsl$\Ubuntu\home\dotnet\projects\legaliser\legaliser-website` is the path from `explorer.exe` (File Explorer). When opening the directory with  `explorer.exe .`. I guess ST just reverse the slash to get a unix path.

I've tried changing `$wsl_working_dir` to `"~/projects/legaliser/legaliser-website"` and `"."` - neither worked and I got the samme error.

```
/bin/bash: line 0: cd: //wsl$/Ubuntu/home/dotnet/projects/legaliser/legaliser-website: No such file or directory
/bin/bash: ./dev.sublime-build: Permission denied
```

`dev.sublime-build` is my build config file - I have absolutely no idea why ST would try to execute that file.

WslBuild is the only plugin (other than Package Control) I have installed.

**Comment by deathaxe** [comment]
I guess it was just the win->unix path translation which failed.

**Comment by dotnetCarpenter** [comment]
Seems like the update will take some time to propagate: https://packagecontrol.io/packages/WslBuild

![image](https://github.com/SublimeText/WslBuild/assets/43763/303dfd15-bb7e-4531-afa9-15e440be6838)

**Comment by deathaxe** [comment]
Yes, normally 4 to 6 hours or so.

**Comment by dotnetCarpenter** [comment]
I did a manual install and can confirm that your package works! 🎉 You are a hero!
